version: "3.9"
services:
  api:
    container_name: budgetwise_api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/budgetwise_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:14
    container_name: budgetwise_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budgetwise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: